import React from 'react';
import { Share2 } from 'lucide-react';

function ShareButton({ animeName, roast, stats }) {
  const handleShare = () => {
    // Format the share text
    const shareText = `🔥 Roast for "${animeName}":

${roast}

📊 Stats: Horniness ${stats.horniness_level}/100 | Plot Armor ${stats.plot_armor_thickness}/100 | Fan Toxicity ${stats.fan_toxicity}/100

Generated by Anime Roast Generator 🎌`;

    // Encode for Twitter
    const encodedText = encodeURIComponent(shareText);
    const twitterUrl = `https://twitter.com/intent/tweet?text=${encodedText}`;
    
    // Open Twitter in new window
    window.open(twitterUrl, '_blank', 'width=600,height=400');
  };

  return (
    <button
      onClick={handleShare}
      className="flex-1 px-4 py-3 bg-[#1f1f1f] hover:bg-[#262626] border border-[#262626] text-white rounded-lg flex items-center justify-center gap-2 transition-colors text-sm"
    >
      <Share2 className="w-4 h-4" />
      <span>Share</span>
    </button>
  );
}

export default ShareButton;
